# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list_dialog_view.ui',
# licensing of 'list_dialog_view.ui' applies.
#
# Created: Thu Feb 28 12:39:11 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ListDialog(object):
    def setupUi(self, ListDialog):
        ListDialog.setObjectName("ListDialog")
        ListDialog.resize(242, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ListDialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dialog_frame = QtWidgets.QFrame(ListDialog)
        self.dialog_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dialog_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dialog_frame.setLineWidth(0)
        self.dialog_frame.setObjectName("dialog_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dialog_frame)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.name_vertical = QtWidgets.QVBoxLayout()
        self.name_vertical.setSpacing(0)
        self.name_vertical.setObjectName("name_vertical")
        self.commodity_label = QtWidgets.QLabel(self.dialog_frame)
        self.commodity_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.commodity_label.setFont(font)
        self.commodity_label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.commodity_label.setObjectName("commodity_label")
        self.name_vertical.addWidget(self.commodity_label)
        self.value_horizontal = QtWidgets.QHBoxLayout()
        self.value_horizontal.setSpacing(10)
        self.value_horizontal.setObjectName("value_horizontal")
        self.commodity_name = PropertyEdit(self.dialog_frame)
        self.commodity_name.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.commodity_name.setFont(font)
        self.commodity_name.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        self.commodity_name.setText("")
        self.commodity_name.setFrame(False)
        self.commodity_name.setObjectName("commodity_name")
        self.value_horizontal.addWidget(self.commodity_name)
        self.button_add = ToolButton(self.dialog_frame)
        self.button_add.setEnabled(False)
        self.button_add.setMaximumSize(QtCore.QSize(22, 22))
        self.button_add.setBaseSize(QtCore.QSize(22, 22))
        self.button_add.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.button_add.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/img/add_normal@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/img/add_select@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.button_add.setIcon(icon)
        self.button_add.setIconSize(QtCore.QSize(22, 22))
        self.button_add.setAutoRaise(True)
        self.button_add.setObjectName("button_add")
        self.value_horizontal.addWidget(self.button_add)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.value_horizontal.addItem(spacerItem)
        self.name_vertical.addLayout(self.value_horizontal)
        self.verticalLayout_3.addLayout(self.name_vertical)
        self.commodity_list = TableView(self.dialog_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.commodity_list.setFont(font)
        self.commodity_list.setMouseTracking(True)
        self.commodity_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.commodity_list.setFrameShadow(QtWidgets.QFrame.Plain)
        self.commodity_list.setLineWidth(0)
        self.commodity_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.commodity_list.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.commodity_list.setAutoScrollMargin(5)
        self.commodity_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.commodity_list.setTabKeyNavigation(False)
        self.commodity_list.setProperty("showDropIndicator", False)
        self.commodity_list.setDragDropOverwriteMode(False)
        self.commodity_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.commodity_list.setShowGrid(False)
        self.commodity_list.setGridStyle(QtCore.Qt.NoPen)
        self.commodity_list.setWordWrap(False)
        self.commodity_list.setCornerButtonEnabled(False)
        self.commodity_list.setObjectName("commodity_list")
        self.commodity_list.horizontalHeader().setVisible(False)
        self.commodity_list.horizontalHeader().setHighlightSections(False)
        self.commodity_list.verticalHeader().setVisible(False)
        self.commodity_list.verticalHeader().setDefaultSectionSize(22)
        self.commodity_list.verticalHeader().setHighlightSections(False)
        self.commodity_list.verticalHeader().setMinimumSectionSize(22)
        self.verticalLayout_3.addWidget(self.commodity_list)
        self.bottom_button_layout = QtWidgets.QHBoxLayout()
        self.bottom_button_layout.setSpacing(-1)
        self.bottom_button_layout.setObjectName("bottom_button_layout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_button_layout.addItem(spacerItem1)
        self.cancel_button = QtWidgets.QPushButton(self.dialog_frame)
        self.cancel_button.setMinimumSize(QtCore.QSize(100, 30))
        self.cancel_button.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        self.cancel_button.setFlat(False)
        self.cancel_button.setObjectName("cancel_button")
        self.bottom_button_layout.addWidget(self.cancel_button)
        self.apply_button = QtWidgets.QPushButton(self.dialog_frame)
        self.apply_button.setMinimumSize(QtCore.QSize(100, 30))
        self.apply_button.setFlat(False)
        self.apply_button.setObjectName("apply_button")
        self.bottom_button_layout.addWidget(self.apply_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_button_layout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.bottom_button_layout)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout.addWidget(self.dialog_frame)

        self.retranslateUi(ListDialog)
        QtCore.QMetaObject.connectSlotsByName(ListDialog)

    def retranslateUi(self, ListDialog):
        ListDialog.setWindowTitle(QtWidgets.QApplication.translate("ListDialog", "Dialog", None, -1))
        self.commodity_label.setText(QtWidgets.QApplication.translate("ListDialog", "Commodity List", None, -1))
        self.cancel_button.setText(QtWidgets.QApplication.translate("ListDialog", "Cancel", None, -1))
        self.apply_button.setText(QtWidgets.QApplication.translate("ListDialog", "OK", None, -1))

from views.components.tool_button import ToolButton
from views.components.table_view import TableView
from views.components.property_edit import PropertyEdit
import osdria_app_rc
