# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'process_dialog_view.ui',
# licensing of 'process_dialog_view.ui' applies.
#
# Created: Sat Apr 13 16:23:30 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ProcessDialog(object):
    def setupUi(self, ProcessDialog):
        ProcessDialog.setObjectName("ProcessDialog")
        ProcessDialog.resize(830, 462)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProcessDialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dialog_frame = QtWidgets.QFrame(ProcessDialog)
        self.dialog_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dialog_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dialog_frame.setLineWidth(0)
        self.dialog_frame.setObjectName("dialog_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dialog_frame)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.top_input_horizontal = QtWidgets.QHBoxLayout()
        self.top_input_horizontal.setSpacing(0)
        self.top_input_horizontal.setObjectName("top_input_horizontal")
        self.name_vertical = QtWidgets.QVBoxLayout()
        self.name_vertical.setSpacing(0)
        self.name_vertical.setObjectName("name_vertical")
        self.process_label = QtWidgets.QLabel(self.dialog_frame)
        self.process_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.process_label.setFont(font)
        self.process_label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.process_label.setObjectName("process_label")
        self.name_vertical.addWidget(self.process_label)
        self.value_horizontal = QtWidgets.QHBoxLayout()
        self.value_horizontal.setSpacing(10)
        self.value_horizontal.setObjectName("value_horizontal")
        self.process_name = PropertyEdit(self.dialog_frame)
        self.process_name.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.process_name.setFont(font)
        self.process_name.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        self.process_name.setText("")
        self.process_name.setFrame(False)
        self.process_name.setObjectName("process_name")
        self.value_horizontal.addWidget(self.process_name)
        self.button_add = ToolButton(self.dialog_frame)
        self.button_add.setEnabled(False)
        self.button_add.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.button_add.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/img/add_normal@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/img/add_select@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.button_add.setIcon(icon)
        self.button_add.setIconSize(QtCore.QSize(22, 22))
        self.button_add.setAutoRaise(True)
        self.button_add.setObjectName("button_add")
        self.value_horizontal.addWidget(self.button_add)
        self.name_vertical.addLayout(self.value_horizontal)
        self.name_vertical.setStretch(1, 1)
        self.top_input_horizontal.addLayout(self.name_vertical)
        spacerItem = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.top_input_horizontal.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.top_input_horizontal)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.section_vertical = QtWidgets.QVBoxLayout()
        self.section_vertical.setSpacing(0)
        self.section_vertical.setObjectName("section_vertical")
        self.section_label = QtWidgets.QLabel(self.dialog_frame)
        self.section_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.section_label.setFont(font)
        self.section_label.setObjectName("section_label")
        self.section_vertical.addWidget(self.section_label)
        self.section_value = PropertyEdit(self.dialog_frame)
        self.section_value.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.section_value.setFont(font)
        self.section_value.setObjectName("section_value")
        self.section_vertical.addWidget(self.section_value)
        self.horizontalLayout.addLayout(self.section_vertical)
        self.category_vertical = QtWidgets.QVBoxLayout()
        self.category_vertical.setSpacing(0)
        self.category_vertical.setObjectName("category_vertical")
        self.category_label = QtWidgets.QLabel(self.dialog_frame)
        self.category_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.category_label.setFont(font)
        self.category_label.setObjectName("category_label")
        self.category_vertical.addWidget(self.category_label)
        self.category_value = PropertyEdit(self.dialog_frame)
        self.category_value.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.category_value.setFont(font)
        self.category_value.setObjectName("category_value")
        self.category_vertical.addWidget(self.category_value)
        self.horizontalLayout.addLayout(self.category_vertical)
        spacerItem1 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.button_icon = QtWidgets.QToolButton(self.dialog_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_icon.sizePolicy().hasHeightForWidth())
        self.button_icon.setSizePolicy(sizePolicy)
        self.button_icon.setMinimumSize(QtCore.QSize(50, 50))
        self.button_icon.setMaximumSize(QtCore.QSize(50, 50))
        self.button_icon.setCursor(QtCore.Qt.PointingHandCursor)
        self.button_icon.setStyleSheet("")
        self.button_icon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/img/process_icon@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_icon.setIcon(icon1)
        self.button_icon.setIconSize(QtCore.QSize(40, 40))
        self.button_icon.setObjectName("button_icon")
        self.horizontalLayout.addWidget(self.button_icon)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.selector_layout = QtWidgets.QHBoxLayout()
        self.selector_layout.setSpacing(5)
        self.selector_layout.setObjectName("selector_layout")
        self.variables_layout = QtWidgets.QVBoxLayout()
        self.variables_layout.setSpacing(0)
        self.variables_layout.setObjectName("variables_layout")
        self.variables_label = QtWidgets.QLabel(self.dialog_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.variables_label.setFont(font)
        self.variables_label.setObjectName("variables_label")
        self.variables_layout.addWidget(self.variables_label)
        self.variables_list = ProcessListView(self.dialog_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.variables_list.setFont(font)
        self.variables_list.setObjectName("variables_list")
        self.variables_layout.addWidget(self.variables_list)
        self.selector_layout.addLayout(self.variables_layout)
        self.data_layout = QtWidgets.QVBoxLayout()
        self.data_layout.setSpacing(0)
        self.data_layout.setObjectName("data_layout")
        self.data_label = QtWidgets.QLabel(self.dialog_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.data_label.setFont(font)
        self.data_label.setObjectName("data_label")
        self.data_layout.addWidget(self.data_label)
        self.data_list = ProcessListView(self.dialog_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.data_list.setFont(font)
        self.data_list.setObjectName("data_list")
        self.data_layout.addWidget(self.data_list)
        self.selector_layout.addLayout(self.data_layout)
        self.properties_layout = QtWidgets.QVBoxLayout()
        self.properties_layout.setSpacing(0)
        self.properties_layout.setObjectName("properties_layout")
        self.properties_label = QtWidgets.QLabel(self.dialog_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.properties_label.setFont(font)
        self.properties_label.setObjectName("properties_label")
        self.properties_layout.addWidget(self.properties_label)
        self.properties_list = ProcessListView(self.dialog_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.properties_list.setFont(font)
        self.properties_list.setObjectName("properties_list")
        self.properties_layout.addWidget(self.properties_list)
        self.selector_layout.addLayout(self.properties_layout)
        self.inputs_layout = QtWidgets.QVBoxLayout()
        self.inputs_layout.setSpacing(0)
        self.inputs_layout.setObjectName("inputs_layout")
        self.inputs_label = QtWidgets.QLabel(self.dialog_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.inputs_label.setFont(font)
        self.inputs_label.setObjectName("inputs_label")
        self.inputs_layout.addWidget(self.inputs_label)
        self.inputs_list = ProcessListView(self.dialog_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.inputs_list.setFont(font)
        self.inputs_list.setObjectName("inputs_list")
        self.inputs_layout.addWidget(self.inputs_list)
        self.selector_layout.addLayout(self.inputs_layout)
        self.outputs_layout = QtWidgets.QVBoxLayout()
        self.outputs_layout.setSpacing(0)
        self.outputs_layout.setObjectName("outputs_layout")
        self.outputs_label = QtWidgets.QLabel(self.dialog_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.outputs_label.setFont(font)
        self.outputs_label.setObjectName("outputs_label")
        self.outputs_layout.addWidget(self.outputs_label)
        self.outputs_list = ProcessListView(self.dialog_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.outputs_list.setFont(font)
        self.outputs_list.setObjectName("outputs_list")
        self.outputs_layout.addWidget(self.outputs_list)
        self.selector_layout.addLayout(self.outputs_layout)
        self.verticalLayout_3.addLayout(self.selector_layout)
        self.objective_vertical = QtWidgets.QVBoxLayout()
        self.objective_vertical.setSpacing(0)
        self.objective_vertical.setObjectName("objective_vertical")
        self.objective_label = QtWidgets.QLabel(self.dialog_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.objective_label.setFont(font)
        self.objective_label.setObjectName("objective_label")
        self.objective_vertical.addWidget(self.objective_label)
        self.objective_value = QtWidgets.QLineEdit(self.dialog_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.objective_value.setFont(font)
        self.objective_value.setObjectName("objective_value")
        self.objective_vertical.addWidget(self.objective_value)
        self.verticalLayout_3.addLayout(self.objective_vertical)
        self.constraints_vertical = QtWidgets.QVBoxLayout()
        self.constraints_vertical.setSpacing(0)
        self.constraints_vertical.setObjectName("constraints_vertical")
        self.constraints_label = QtWidgets.QLabel(self.dialog_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.constraints_label.setFont(font)
        self.constraints_label.setObjectName("constraints_label")
        self.constraints_vertical.addWidget(self.constraints_label)
        self.constraints_value = QtWidgets.QTextEdit(self.dialog_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.constraints_value.setFont(font)
        self.constraints_value.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        self.constraints_value.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.constraints_value.setFrameShadow(QtWidgets.QFrame.Plain)
        self.constraints_value.setLineWidth(0)
        self.constraints_value.setObjectName("constraints_value")
        self.constraints_vertical.addWidget(self.constraints_value)
        self.verticalLayout_3.addLayout(self.constraints_vertical)
        self.bottom_button_layout = QtWidgets.QHBoxLayout()
        self.bottom_button_layout.setSpacing(-1)
        self.bottom_button_layout.setObjectName("bottom_button_layout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_button_layout.addItem(spacerItem2)
        self.cancel_button = QtWidgets.QPushButton(self.dialog_frame)
        self.cancel_button.setMinimumSize(QtCore.QSize(100, 30))
        self.cancel_button.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        self.cancel_button.setFlat(False)
        self.cancel_button.setObjectName("cancel_button")
        self.bottom_button_layout.addWidget(self.cancel_button)
        self.apply_button = QtWidgets.QPushButton(self.dialog_frame)
        self.apply_button.setMinimumSize(QtCore.QSize(100, 30))
        self.apply_button.setFlat(False)
        self.apply_button.setObjectName("apply_button")
        self.bottom_button_layout.addWidget(self.apply_button)
        self.verticalLayout_3.addLayout(self.bottom_button_layout)
        self.verticalLayout.addWidget(self.dialog_frame)

        self.retranslateUi(ProcessDialog)
        QtCore.QMetaObject.connectSlotsByName(ProcessDialog)

    def retranslateUi(self, ProcessDialog):
        ProcessDialog.setWindowTitle(QtWidgets.QApplication.translate("ProcessDialog", "Dialog", None, -1))
        self.process_label.setText(QtWidgets.QApplication.translate("ProcessDialog", "Process Name", None, -1))
        self.section_label.setText(QtWidgets.QApplication.translate("ProcessDialog", "Section", None, -1))
        self.category_label.setText(QtWidgets.QApplication.translate("ProcessDialog", "Category", None, -1))
        self.variables_label.setText(QtWidgets.QApplication.translate("ProcessDialog", "Variables", None, -1))
        self.data_label.setText(QtWidgets.QApplication.translate("ProcessDialog", "Data", None, -1))
        self.properties_label.setText(QtWidgets.QApplication.translate("ProcessDialog", "Properties", None, -1))
        self.inputs_label.setText(QtWidgets.QApplication.translate("ProcessDialog", "Inputs", None, -1))
        self.outputs_label.setText(QtWidgets.QApplication.translate("ProcessDialog", "Outputs", None, -1))
        self.objective_label.setText(QtWidgets.QApplication.translate("ProcessDialog", "Objective Function", None, -1))
        self.constraints_label.setText(QtWidgets.QApplication.translate("ProcessDialog", "Constraints", None, -1))
        self.cancel_button.setText(QtWidgets.QApplication.translate("ProcessDialog", "Cancel", None, -1))
        self.apply_button.setText(QtWidgets.QApplication.translate("ProcessDialog", "OK", None, -1))

from views.components.property_edit import PropertyEdit
from views.components.tool_button import ToolButton
from views.components.process_list_view import ProcessListView
import osdria_app_rc
