# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_view.ui',
# licensing of 'project_view.ui' applies.
#
# Created: Thu Apr 18 11:19:59 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1327, 775)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stacked_pages = QtWidgets.QStackedWidget(self.centralwidget)
        self.stacked_pages.setLineWidth(0)
        self.stacked_pages.setObjectName("stacked_pages")
        self.overview = QtWidgets.QWidget()
        self.overview.setObjectName("overview")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.overview)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolbar_overview = QtWidgets.QFrame(self.overview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbar_overview.sizePolicy().hasHeightForWidth())
        self.toolbar_overview.setSizePolicy(sizePolicy)
        self.toolbar_overview.setMinimumSize(QtCore.QSize(0, 0))
        self.toolbar_overview.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolbar_overview.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolbar_overview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolbar_overview.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolbar_overview.setLineWidth(0)
        self.toolbar_overview.setObjectName("toolbar_overview")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.toolbar_overview)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(250, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.tool_scenarios = ToolButton(self.toolbar_overview)
        self.tool_scenarios.setEnabled(False)
        self.tool_scenarios.setMinimumSize(QtCore.QSize(50, 50))
        self.tool_scenarios.setSizeIncrement(QtCore.QSize(0, 0))
        self.tool_scenarios.setBaseSize(QtCore.QSize(50, 50))
        self.tool_scenarios.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/img/scenarios_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/img/scenarios_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.tool_scenarios.setIcon(icon)
        self.tool_scenarios.setIconSize(QtCore.QSize(30, 30))
        self.tool_scenarios.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tool_scenarios.setObjectName("tool_scenarios")
        self.horizontalLayout.addWidget(self.tool_scenarios)
        self.scenario_select = PropertyEdit(self.toolbar_overview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scenario_select.sizePolicy().hasHeightForWidth())
        self.scenario_select.setSizePolicy(sizePolicy)
        self.scenario_select.setMinimumSize(QtCore.QSize(200, 30))
        self.scenario_select.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.scenario_select.setFont(font)
        self.scenario_select.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        self.scenario_select.setReadOnly(True)
        self.scenario_select.setClearButtonEnabled(False)
        self.scenario_select.setObjectName("scenario_select")
        self.horizontalLayout.addWidget(self.scenario_select)
        self.tool_run = ToolButton(self.toolbar_overview)
        self.tool_run.setEnabled(False)
        self.tool_run.setMinimumSize(QtCore.QSize(50, 50))
        self.tool_run.setBaseSize(QtCore.QSize(50, 50))
        self.tool_run.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/img/run_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icons/img/run_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.tool_run.setIcon(icon1)
        self.tool_run.setIconSize(QtCore.QSize(30, 30))
        self.tool_run.setObjectName("tool_run")
        self.horizontalLayout.addWidget(self.tool_run)
        self.tool_export = ToolButton(self.toolbar_overview)
        self.tool_export.setEnabled(False)
        self.tool_export.setMinimumSize(QtCore.QSize(50, 50))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/img/export_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icons/img/export_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.tool_export.setIcon(icon2)
        self.tool_export.setIconSize(QtCore.QSize(30, 30))
        self.tool_export.setObjectName("tool_export")
        self.horizontalLayout.addWidget(self.tool_export)
        spacerItem1 = QtWidgets.QSpacerItem(0, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.title_overview = QtWidgets.QLabel(self.toolbar_overview)
        self.title_overview.setMinimumSize(QtCore.QSize(0, 50))
        self.title_overview.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setWeight(50)
        font.setBold(False)
        self.title_overview.setFont(font)
        self.title_overview.setLineWidth(0)
        self.title_overview.setAlignment(QtCore.Qt.AlignCenter)
        self.title_overview.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.title_overview.setObjectName("title_overview")
        self.horizontalLayout.addWidget(self.title_overview)
        spacerItem2 = QtWidgets.QSpacerItem(0, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(550, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.tool_sidebar_overview = ToolButton(self.toolbar_overview)
        self.tool_sidebar_overview.setEnabled(False)
        self.tool_sidebar_overview.setMinimumSize(QtCore.QSize(50, 50))
        self.tool_sidebar_overview.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/img/sidebar_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icons/img/sidebar_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.tool_sidebar_overview.setIcon(icon3)
        self.tool_sidebar_overview.setIconSize(QtCore.QSize(30, 30))
        self.tool_sidebar_overview.setCheckable(False)
        self.tool_sidebar_overview.setChecked(False)
        self.tool_sidebar_overview.setObjectName("tool_sidebar_overview")
        self.horizontalLayout.addWidget(self.tool_sidebar_overview)
        self.horizontalLayout.setStretch(5, 1)
        self.horizontalLayout.setStretch(7, 1)
        self.verticalLayout.addWidget(self.toolbar_overview)
        self.main_overview = QtWidgets.QFrame(self.overview)
        self.main_overview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_overview.setFrameShadow(QtWidgets.QFrame.Plain)
        self.main_overview.setLineWidth(0)
        self.main_overview.setObjectName("main_overview")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_overview)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo_frame = QtWidgets.QFrame(self.main_overview)
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setLineWidth(0)
        self.logo_frame.setObjectName("logo_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.logo_frame)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.layoutLogo = QtWidgets.QVBoxLayout()
        self.layoutLogo.setSpacing(0)
        self.layoutLogo.setObjectName("layoutLogo")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layoutLogo.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.layoutLogo.addItem(spacerItem6)
        self.logo = SectionSelector(self.logo_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(100, 100))
        self.logo.setMouseTracking(True)
        self.logo.setLineWidth(0)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/icons/img/logo_light@2x.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.layoutLogo.addWidget(self.logo)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layoutLogo.addItem(spacerItem7)
        self.horizontalLayout_3.addLayout(self.layoutLogo)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.horizontalLayout_2.addWidget(self.logo_frame)
        self.sidebar_overview = Sidebar(self.main_overview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar_overview.sizePolicy().hasHeightForWidth())
        self.sidebar_overview.setSizePolicy(sizePolicy)
        self.sidebar_overview.setMinimumSize(QtCore.QSize(0, 0))
        self.sidebar_overview.setMaximumSize(QtCore.QSize(260, 16777215))
        self.sidebar_overview.setBaseSize(QtCore.QSize(260, 0))
        self.sidebar_overview.setStyleSheet("")
        self.sidebar_overview.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sidebar_overview.setLineWidth(0)
        self.sidebar_overview.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sidebar_overview.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.sidebar_overview.setObjectName("sidebar_overview")
        self.horizontalLayout_2.addWidget(self.sidebar_overview)
        self.verticalLayout.addWidget(self.main_overview)
        self.stacked_pages.addWidget(self.overview)
        self.sections = QtWidgets.QWidget()
        self.sections.setObjectName("sections")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sections)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolbar_sections = QtWidgets.QFrame(self.sections)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbar_sections.sizePolicy().hasHeightForWidth())
        self.toolbar_sections.setSizePolicy(sizePolicy)
        self.toolbar_sections.setMinimumSize(QtCore.QSize(0, 0))
        self.toolbar_sections.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolbar_sections.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolbar_sections.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolbar_sections.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolbar_sections.setLineWidth(0)
        self.toolbar_sections.setObjectName("toolbar_sections")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.toolbar_sections)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tool_back_sections = ToolButton(self.toolbar_sections)
        self.tool_back_sections.setEnabled(False)
        self.tool_back_sections.setMinimumSize(QtCore.QSize(50, 50))
        self.tool_back_sections.setSizeIncrement(QtCore.QSize(0, 0))
        self.tool_back_sections.setBaseSize(QtCore.QSize(0, 0))
        self.tool_back_sections.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/img/back_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/icons/img/back_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.tool_back_sections.setIcon(icon4)
        self.tool_back_sections.setIconSize(QtCore.QSize(30, 30))
        self.tool_back_sections.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tool_back_sections.setObjectName("tool_back_sections")
        self.horizontalLayout_4.addWidget(self.tool_back_sections)
        self.tool_draft = ToolButton(self.toolbar_sections)
        self.tool_draft.setEnabled(False)
        self.tool_draft.setMinimumSize(QtCore.QSize(50, 50))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/img/draft_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/icons/img/draft_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.tool_draft.setIcon(icon5)
        self.tool_draft.setIconSize(QtCore.QSize(30, 30))
        self.tool_draft.setCheckable(False)
        self.tool_draft.setObjectName("tool_draft")
        self.horizontalLayout_4.addWidget(self.tool_draft)
        spacerItem9 = QtWidgets.QSpacerItem(40, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.title_sections = QtWidgets.QLabel(self.toolbar_sections)
        self.title_sections.setMinimumSize(QtCore.QSize(0, 50))
        self.title_sections.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        self.title_sections.setFont(font)
        self.title_sections.setLineWidth(0)
        self.title_sections.setAlignment(QtCore.Qt.AlignCenter)
        self.title_sections.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.title_sections.setObjectName("title_sections")
        self.horizontalLayout_4.addWidget(self.title_sections)
        spacerItem10 = QtWidgets.QSpacerItem(40, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(50, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.tool_sidebar_sections = ToolButton(self.toolbar_sections)
        self.tool_sidebar_sections.setEnabled(False)
        self.tool_sidebar_sections.setMinimumSize(QtCore.QSize(50, 50))
        self.tool_sidebar_sections.setMaximumSize(QtCore.QSize(50, 50))
        self.tool_sidebar_sections.setIcon(icon3)
        self.tool_sidebar_sections.setIconSize(QtCore.QSize(30, 30))
        self.tool_sidebar_sections.setCheckable(False)
        self.tool_sidebar_sections.setObjectName("tool_sidebar_sections")
        self.horizontalLayout_4.addWidget(self.tool_sidebar_sections)
        self.verticalLayout_2.addWidget(self.toolbar_sections)
        self.main_sections = QtWidgets.QHBoxLayout()
        self.main_sections.setSpacing(0)
        self.main_sections.setObjectName("main_sections")
        self.section_view = SceneView(self.sections)
        self.section_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.section_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.section_view.setObjectName("section_view")
        self.main_sections.addWidget(self.section_view)
        self.sidebar_sections = Sidebar(self.sections)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar_sections.sizePolicy().hasHeightForWidth())
        self.sidebar_sections.setSizePolicy(sizePolicy)
        self.sidebar_sections.setMaximumSize(QtCore.QSize(260, 16777215))
        self.sidebar_sections.setBaseSize(QtCore.QSize(260, 0))
        self.sidebar_sections.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sidebar_sections.setLineWidth(0)
        self.sidebar_sections.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sidebar_sections.setObjectName("sidebar_sections")
        self.main_sections.addWidget(self.sidebar_sections)
        self.verticalLayout_2.addLayout(self.main_sections)
        self.verticalLayout_2.setStretch(1, 1)
        self.stacked_pages.addWidget(self.sections)
        self.draft = QtWidgets.QWidget()
        self.draft.setObjectName("draft")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.draft)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolbar_draft = QtWidgets.QFrame(self.draft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbar_draft.sizePolicy().hasHeightForWidth())
        self.toolbar_draft.setSizePolicy(sizePolicy)
        self.toolbar_draft.setMinimumSize(QtCore.QSize(0, 0))
        self.toolbar_draft.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolbar_draft.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolbar_draft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolbar_draft.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolbar_draft.setLineWidth(0)
        self.toolbar_draft.setObjectName("toolbar_draft")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.toolbar_draft)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem12 = QtWidgets.QSpacerItem(50, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.tool_back_draft = ToolButton(self.toolbar_draft)
        self.tool_back_draft.setEnabled(False)
        self.tool_back_draft.setMinimumSize(QtCore.QSize(50, 50))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/img/draft_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icons/img/draft_select_orange@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.tool_back_draft.setIcon(icon6)
        self.tool_back_draft.setIconSize(QtCore.QSize(30, 30))
        self.tool_back_draft.setCheckable(False)
        self.tool_back_draft.setChecked(False)
        self.tool_back_draft.setObjectName("tool_back_draft")
        self.horizontalLayout_5.addWidget(self.tool_back_draft)
        spacerItem13 = QtWidgets.QSpacerItem(150, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.tool_cursor = ToolButton(self.toolbar_draft)
        self.tool_cursor.setEnabled(False)
        self.tool_cursor.setMinimumSize(QtCore.QSize(50, 50))
        self.tool_cursor.setBaseSize(QtCore.QSize(50, 50))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/img/cursor_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icons/img/cursor_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icons/img/cursor_select_orange@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.tool_cursor.setIcon(icon7)
        self.tool_cursor.setIconSize(QtCore.QSize(30, 30))
        self.tool_cursor.setCheckable(True)
        self.tool_cursor.setChecked(True)
        self.tool_cursor.setObjectName("tool_cursor")
        self.horizontalLayout_5.addWidget(self.tool_cursor)
        self.tool_connect = ToolButton(self.toolbar_draft)
        self.tool_connect.setEnabled(False)
        self.tool_connect.setMinimumSize(QtCore.QSize(50, 50))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/img/connect_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icons/img/connect_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icons/img/connect_select_orange@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.tool_connect.setIcon(icon8)
        self.tool_connect.setIconSize(QtCore.QSize(30, 30))
        self.tool_connect.setCheckable(True)
        self.tool_connect.setObjectName("tool_connect")
        self.horizontalLayout_5.addWidget(self.tool_connect)
        spacerItem14 = QtWidgets.QSpacerItem(40, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.title_draft = QtWidgets.QLabel(self.toolbar_draft)
        self.title_draft.setMinimumSize(QtCore.QSize(0, 50))
        self.title_draft.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        self.title_draft.setFont(font)
        self.title_draft.setLineWidth(0)
        self.title_draft.setAlignment(QtCore.Qt.AlignCenter)
        self.title_draft.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.title_draft.setObjectName("title_draft")
        self.horizontalLayout_5.addWidget(self.title_draft)
        spacerItem15 = QtWidgets.QSpacerItem(40, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(300, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem16)
        self.tool_sidebar_draft = ToolButton(self.toolbar_draft)
        self.tool_sidebar_draft.setEnabled(False)
        self.tool_sidebar_draft.setMinimumSize(QtCore.QSize(50, 50))
        self.tool_sidebar_draft.setMaximumSize(QtCore.QSize(50, 50))
        self.tool_sidebar_draft.setIcon(icon3)
        self.tool_sidebar_draft.setIconSize(QtCore.QSize(30, 30))
        self.tool_sidebar_draft.setObjectName("tool_sidebar_draft")
        self.horizontalLayout_5.addWidget(self.tool_sidebar_draft)
        self.verticalLayout_4.addWidget(self.toolbar_draft)
        self.mainDraft = QtWidgets.QHBoxLayout()
        self.mainDraft.setSpacing(0)
        self.mainDraft.setObjectName("mainDraft")
        self.draftbar = Sidebar(self.draft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.draftbar.sizePolicy().hasHeightForWidth())
        self.draftbar.setSizePolicy(sizePolicy)
        self.draftbar.setBaseSize(QtCore.QSize(260, 0))
        self.draftbar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.draftbar.setLineWidth(0)
        self.draftbar.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.draftbar.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.draftbar.setObjectName("draftbar")
        self.mainDraft.addWidget(self.draftbar)
        self.draft_view = SceneView(self.draft)
        self.draft_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.draft_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.draft_view.setObjectName("draft_view")
        self.mainDraft.addWidget(self.draft_view)
        self.sidebar_draft = Sidebar(self.draft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar_draft.sizePolicy().hasHeightForWidth())
        self.sidebar_draft.setSizePolicy(sizePolicy)
        self.sidebar_draft.setMaximumSize(QtCore.QSize(260, 16777215))
        self.sidebar_draft.setBaseSize(QtCore.QSize(260, 0))
        self.sidebar_draft.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sidebar_draft.setObjectName("sidebar_draft")
        self.mainDraft.addWidget(self.sidebar_draft)
        self.verticalLayout_4.addLayout(self.mainDraft)
        self.verticalLayout_4.setStretch(1, 1)
        self.stacked_pages.addWidget(self.draft)
        self.graph = QtWidgets.QWidget()
        self.graph.setObjectName("graph")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.graph)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.toolbar_graph = QtWidgets.QFrame(self.graph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbar_graph.sizePolicy().hasHeightForWidth())
        self.toolbar_graph.setSizePolicy(sizePolicy)
        self.toolbar_graph.setMinimumSize(QtCore.QSize(0, 0))
        self.toolbar_graph.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolbar_graph.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolbar_graph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolbar_graph.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolbar_graph.setLineWidth(0)
        self.toolbar_graph.setObjectName("toolbar_graph")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.toolbar_graph)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tool_back_graph = ToolButton(self.toolbar_graph)
        self.tool_back_graph.setEnabled(False)
        self.tool_back_graph.setMinimumSize(QtCore.QSize(50, 50))
        self.tool_back_graph.setSizeIncrement(QtCore.QSize(0, 0))
        self.tool_back_graph.setBaseSize(QtCore.QSize(50, 50))
        self.tool_back_graph.setText("")
        self.tool_back_graph.setIcon(icon4)
        self.tool_back_graph.setIconSize(QtCore.QSize(30, 30))
        self.tool_back_graph.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tool_back_graph.setObjectName("tool_back_graph")
        self.horizontalLayout_6.addWidget(self.tool_back_graph)
        spacerItem17 = QtWidgets.QSpacerItem(200, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.commodity_select = PropertyEdit(self.toolbar_graph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commodity_select.sizePolicy().hasHeightForWidth())
        self.commodity_select.setSizePolicy(sizePolicy)
        self.commodity_select.setBaseSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.commodity_select.setFont(font)
        self.commodity_select.setReadOnly(True)
        self.commodity_select.setObjectName("commodity_select")
        self.horizontalLayout_6.addWidget(self.commodity_select)
        self.tool_export_graph = ToolButton(self.toolbar_graph)
        self.tool_export_graph.setEnabled(False)
        self.tool_export_graph.setMinimumSize(QtCore.QSize(50, 50))
        self.tool_export_graph.setBaseSize(QtCore.QSize(50, 50))
        self.tool_export_graph.setIcon(icon2)
        self.tool_export_graph.setIconSize(QtCore.QSize(30, 30))
        self.tool_export_graph.setObjectName("tool_export_graph")
        self.horizontalLayout_6.addWidget(self.tool_export_graph)
        spacerItem18 = QtWidgets.QSpacerItem(0, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem18)
        self.title_graph = QtWidgets.QLabel(self.toolbar_graph)
        self.title_graph.setMinimumSize(QtCore.QSize(0, 0))
        self.title_graph.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        self.title_graph.setFont(font)
        self.title_graph.setLineWidth(0)
        self.title_graph.setAlignment(QtCore.Qt.AlignCenter)
        self.title_graph.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.title_graph.setObjectName("title_graph")
        self.horizontalLayout_6.addWidget(self.title_graph)
        spacerItem19 = QtWidgets.QSpacerItem(0, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem19)
        self.tool_cursor_graph = ToolButton(self.toolbar_graph)
        self.tool_cursor_graph.setEnabled(False)
        self.tool_cursor_graph.setMinimumSize(QtCore.QSize(50, 50))
        self.tool_cursor_graph.setIcon(icon7)
        self.tool_cursor_graph.setIconSize(QtCore.QSize(30, 30))
        self.tool_cursor_graph.setCheckable(True)
        self.tool_cursor_graph.setChecked(True)
        self.tool_cursor_graph.setObjectName("tool_cursor_graph")
        self.horizontalLayout_6.addWidget(self.tool_cursor_graph)
        self.tool_zoom_in = ToolButton(self.toolbar_graph)
        self.tool_zoom_in.setEnabled(False)
        self.tool_zoom_in.setMinimumSize(QtCore.QSize(50, 50))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/img/zoom-in_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/icons/img/zoom-in_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/icons/img/zoom-in_select_orange@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.tool_zoom_in.setIcon(icon9)
        self.tool_zoom_in.setIconSize(QtCore.QSize(30, 30))
        self.tool_zoom_in.setCheckable(True)
        self.tool_zoom_in.setObjectName("tool_zoom_in")
        self.horizontalLayout_6.addWidget(self.tool_zoom_in)
        self.tool_zoom_out = ToolButton(self.toolbar_graph)
        self.tool_zoom_out.setEnabled(False)
        self.tool_zoom_out.setMinimumSize(QtCore.QSize(50, 50))
        self.tool_zoom_out.setMaximumSize(QtCore.QSize(50, 50))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/img/zoom-out_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":/icons/img/zoom-out_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":/icons/img/zoom-out_select_orange@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.tool_zoom_out.setIcon(icon10)
        self.tool_zoom_out.setIconSize(QtCore.QSize(30, 30))
        self.tool_zoom_out.setCheckable(True)
        self.tool_zoom_out.setObjectName("tool_zoom_out")
        self.horizontalLayout_6.addWidget(self.tool_zoom_out)
        self.tool_zoom_range = ToolButton(self.toolbar_graph)
        self.tool_zoom_range.setEnabled(False)
        self.tool_zoom_range.setMinimumSize(QtCore.QSize(50, 50))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/img/zoom-range_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap(":/icons/img/zoom-range_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap(":/icons/img/zoom-range_select_orange@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.tool_zoom_range.setIcon(icon11)
        self.tool_zoom_range.setIconSize(QtCore.QSize(30, 30))
        self.tool_zoom_range.setCheckable(True)
        self.tool_zoom_range.setObjectName("tool_zoom_range")
        self.horizontalLayout_6.addWidget(self.tool_zoom_range)
        spacerItem20 = QtWidgets.QSpacerItem(300, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem20)
        self.horizontalLayout_6.setStretch(8, 1)
        self.horizontalLayout_6.setStretch(10, 1)
        self.verticalLayout_5.addWidget(self.toolbar_graph)
        self.main_graph = QtWidgets.QVBoxLayout()
        self.main_graph.setSpacing(0)
        self.main_graph.setObjectName("main_graph")
        self.commodity_flow_view = FlowGraph(self.graph)
        self.commodity_flow_view.setObjectName("commodity_flow_view")
        self.main_graph.addWidget(self.commodity_flow_view)
        self.commodity_storage_view = QtWidgets.QGraphicsView(self.graph)
        self.commodity_storage_view.setObjectName("commodity_storage_view")
        self.main_graph.addWidget(self.commodity_storage_view)
        self.main_graph.setStretch(0, 2)
        self.main_graph.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.main_graph)
        self.verticalLayout_5.setStretch(1, 1)
        self.stacked_pages.addWidget(self.graph)
        self.verticalLayout_3.addWidget(self.stacked_pages)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1327, 22))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_model = QtWidgets.QMenu(self.menubar)
        self.menu_model.setObjectName("menu_model")
        self.menu_run = QtWidgets.QMenu(self.menubar)
        self.menu_run.setObjectName("menu_run")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_close = QtWidgets.QAction(MainWindow)
        self.action_close.setObjectName("action_close")
        self.action_processes = QtWidgets.QAction(MainWindow)
        self.action_processes.setObjectName("action_processes")
        self.action_commodities = QtWidgets.QAction(MainWindow)
        self.action_commodities.setObjectName("action_commodities")
        self.action_scenarios = QtWidgets.QAction(MainWindow)
        self.action_scenarios.setObjectName("action_scenarios")
        self.action_execute = QtWidgets.QAction(MainWindow)
        self.action_execute.setObjectName("action_execute")
        self.action_timeseries = QtWidgets.QAction(MainWindow)
        self.action_timeseries.setObjectName("action_timeseries")
        self.menu_file.addAction(self.action_save)
        self.menu_file.addAction(self.action_close)
        self.menu_model.addAction(self.action_processes)
        self.menu_model.addAction(self.action_commodities)
        self.menu_model.addAction(self.action_timeseries)
        self.menu_run.addAction(self.action_scenarios)
        self.menu_run.addAction(self.action_execute)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_model.menuAction())
        self.menubar.addAction(self.menu_run.menuAction())

        self.retranslateUi(MainWindow)
        self.stacked_pages.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.scenario_select.setText(QtWidgets.QApplication.translate("MainWindow", "Scenario", None, -1))
        self.tool_run.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.tool_export.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.title_overview.setText(QtWidgets.QApplication.translate("MainWindow", "Overview", None, -1))
        self.tool_sidebar_overview.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.tool_draft.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.title_sections.setText(QtWidgets.QApplication.translate("MainWindow", "Energy", None, -1))
        self.tool_sidebar_sections.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.tool_back_draft.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.tool_cursor.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.tool_connect.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.title_draft.setText(QtWidgets.QApplication.translate("MainWindow", "Energy - Draft", None, -1))
        self.tool_sidebar_draft.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.commodity_select.setText(QtWidgets.QApplication.translate("MainWindow", "Commodity", None, -1))
        self.tool_export_graph.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.title_graph.setText(QtWidgets.QApplication.translate("MainWindow", "Commodity", None, -1))
        self.tool_cursor_graph.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.tool_zoom_in.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.tool_zoom_out.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.tool_zoom_range.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.menu_file.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menu_model.setTitle(QtWidgets.QApplication.translate("MainWindow", "Model", None, -1))
        self.menu_run.setTitle(QtWidgets.QApplication.translate("MainWindow", "Run", None, -1))
        self.action_save.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.action_save.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1))
        self.action_close.setText(QtWidgets.QApplication.translate("MainWindow", "Close", None, -1))
        self.action_close.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None, -1))
        self.action_processes.setText(QtWidgets.QApplication.translate("MainWindow", "Processes", None, -1))
        self.action_processes.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+P", None, -1))
        self.action_commodities.setText(QtWidgets.QApplication.translate("MainWindow", "Commodities", None, -1))
        self.action_commodities.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+C", None, -1))
        self.action_scenarios.setText(QtWidgets.QApplication.translate("MainWindow", "Scenarios", None, -1))
        self.action_scenarios.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, -1))
        self.action_execute.setText(QtWidgets.QApplication.translate("MainWindow", "Execute", None, -1))
        self.action_execute.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+R", None, -1))
        self.action_timeseries.setText(QtWidgets.QApplication.translate("MainWindow", "Timeseries", None, -1))
        self.action_timeseries.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+T", None, -1))

from views.components.sidebar import Sidebar
from views.components.property_edit import PropertyEdit
from views.components.tool_button import ToolButton
from views.components.flow_graph import FlowGraph
from views.components.scene_view import SceneView
from views.components.section_selector import SectionSelector
import osdria_app_rc
import osdria_app_rc
