# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome_view.ui',
# licensing of 'welcome_view.ui' applies.
#
# Created: Sun Feb 10 18:45:13 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(450, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setWindowOpacity(1.0)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        Dialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_main = QtWidgets.QFrame(Dialog)
        self.frame_main.setMouseTracking(False)
        self.frame_main.setAutoFillBackground(False)
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_main.setLineWidth(0)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayoutClose = QtWidgets.QHBoxLayout()
        self.horizontalLayoutClose.setSpacing(0)
        self.horizontalLayoutClose.setContentsMargins(10, 5, -1, -1)
        self.horizontalLayoutClose.setObjectName("horizontalLayoutClose")
        self.button_close = ToolButton(self.frame_main)
        self.button_close.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_close.sizePolicy().hasHeightForWidth())
        self.button_close.setSizePolicy(sizePolicy)
        self.button_close.setMinimumSize(QtCore.QSize(11, 11))
        self.button_close.setMaximumSize(QtCore.QSize(11, 11))
        self.button_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/img/close_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/img/close_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.button_close.setIcon(icon)
        self.button_close.setIconSize(QtCore.QSize(11, 11))
        self.button_close.setCheckable(False)
        self.button_close.setChecked(False)
        self.button_close.setObjectName("button_close")
        self.horizontalLayoutClose.addWidget(self.button_close)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutClose.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayoutClose)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayoutContent = QtWidgets.QHBoxLayout()
        self.horizontalLayoutContent.setSpacing(0)
        self.horizontalLayoutContent.setObjectName("horizontalLayoutContent")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutContent.addItem(spacerItem2)
        self.verticalLayoutContent = QtWidgets.QVBoxLayout()
        self.verticalLayoutContent.setSpacing(5)
        self.verticalLayoutContent.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayoutContent.setObjectName("verticalLayoutContent")
        self.iconLogo = QtWidgets.QLabel(self.frame_main)
        self.iconLogo.setText("")
        self.iconLogo.setPixmap(QtGui.QPixmap(":/icons/img/logo@2x.png"))
        self.iconLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.iconLogo.setObjectName("iconLogo")
        self.verticalLayoutContent.addWidget(self.iconLogo)
        self.labelWelcome = QtWidgets.QLabel(self.frame_main)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        self.labelWelcome.setFont(font)
        self.labelWelcome.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWelcome.setObjectName("labelWelcome")
        self.verticalLayoutContent.addWidget(self.labelWelcome)
        self.frame_create = ProjectButton(self.frame_main)
        self.frame_create.setCursor(QtCore.Qt.PointingHandCursor)
        self.frame_create.setObjectName("frame_create")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_create)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.iconCreate = QtWidgets.QLabel(self.frame_create)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconCreate.sizePolicy().hasHeightForWidth())
        self.iconCreate.setSizePolicy(sizePolicy)
        self.iconCreate.setText("")
        self.iconCreate.setPixmap(QtGui.QPixmap(":/icons/img/new@2x.png"))
        self.iconCreate.setAlignment(QtCore.Qt.AlignCenter)
        self.iconCreate.setObjectName("iconCreate")
        self.horizontalLayout_3.addWidget(self.iconCreate)
        self.textLayoutCreate = QtWidgets.QVBoxLayout()
        self.textLayoutCreate.setSpacing(0)
        self.textLayoutCreate.setObjectName("textLayoutCreate")
        self.labelCreateTitle = QtWidgets.QLabel(self.frame_create)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.labelCreateTitle.setFont(font)
        self.labelCreateTitle.setObjectName("labelCreateTitle")
        self.textLayoutCreate.addWidget(self.labelCreateTitle)
        self.labelCreateSub = QtWidgets.QLabel(self.frame_create)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.labelCreateSub.setFont(font)
        self.labelCreateSub.setObjectName("labelCreateSub")
        self.textLayoutCreate.addWidget(self.labelCreateSub)
        self.horizontalLayout_3.addLayout(self.textLayoutCreate)
        self.verticalLayoutContent.addWidget(self.frame_create)
        self.frame_open = ProjectButton(self.frame_main)
        self.frame_open.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_open.setCursor(QtCore.Qt.PointingHandCursor)
        self.frame_open.setObjectName("frame_open")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_open)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.iconOpen = QtWidgets.QLabel(self.frame_open)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconOpen.sizePolicy().hasHeightForWidth())
        self.iconOpen.setSizePolicy(sizePolicy)
        self.iconOpen.setText("")
        self.iconOpen.setPixmap(QtGui.QPixmap(":/icons/img/open@2x.png"))
        self.iconOpen.setAlignment(QtCore.Qt.AlignCenter)
        self.iconOpen.setObjectName("iconOpen")
        self.horizontalLayout_4.addWidget(self.iconOpen)
        self.textLayoutOpen = QtWidgets.QVBoxLayout()
        self.textLayoutOpen.setSpacing(0)
        self.textLayoutOpen.setObjectName("textLayoutOpen")
        self.labelOpenTitle = QtWidgets.QLabel(self.frame_open)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.labelOpenTitle.setFont(font)
        self.labelOpenTitle.setObjectName("labelOpenTitle")
        self.textLayoutOpen.addWidget(self.labelOpenTitle)
        self.labelOpenSub = QtWidgets.QLabel(self.frame_open)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.labelOpenSub.setFont(font)
        self.labelOpenSub.setObjectName("labelOpenSub")
        self.textLayoutOpen.addWidget(self.labelOpenSub)
        self.horizontalLayout_4.addLayout(self.textLayoutOpen)
        self.verticalLayoutContent.addWidget(self.frame_open)
        self.horizontalLayoutContent.addLayout(self.verticalLayoutContent)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutContent.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayoutContent)
        spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(3, 1)
        self.gridLayout.addWidget(self.frame_main, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.labelWelcome.setText(QtWidgets.QApplication.translate("Dialog", "Welcome to OSDRIA", None, -1))
        self.labelCreateTitle.setText(QtWidgets.QApplication.translate("Dialog", "Create ...", None, -1))
        self.labelCreateSub.setText(QtWidgets.QApplication.translate("Dialog", "New OSDRIA project", None, -1))
        self.labelOpenTitle.setText(QtWidgets.QApplication.translate("Dialog", "Open ...", None, -1))
        self.labelOpenSub.setText(QtWidgets.QApplication.translate("Dialog", "Existing OSDRIA project", None, -1))

from views.components.tool_button import ToolButton
from views.components.project_button import ProjectButton
import osdria_app_rc
import osdria_app_rc
